import type { Experiment, ScoringWeights } from "./types";

export const defaultWeights: ScoringWeights = {
  corrosion: 50,
  hardness: 25,
  microstructure: 25,
};

export const sourceExperiments: Experiment[] = [
  {
    id: "smaw-160",
    specimen: "SMAW 160 A",
    process: "SMAW",
    current: 160,
    travelSpeed: 5.76,
    initialMass: 5.382,
    finalMass: 4.663,
    massLossPercent: 13.36,
    corrosionRate: 26.04,
    finalMeasurementDay: 28,
    ocpMonitoredToDay: 28,
    microstructureStatus: "complete",
    microstructureScore: 85,
    microstructureNote:
      "EDS (Phenom 15kV): 70.10 wt% Fe, 17.63 wt% Cr, 6.31 wt% Ni, 1.58 wt% Zn, 0.92 wt% Cu, 0.75 wt% Si; clean matrix with 0.00% Cl and 0.00% Na. XRD: 44(8) wt% Fe, 31(6) wt% Cr, 25(11) wt% Ni; excellent Cr retention.",
    hardness: {
      baseMetal: 180,
      haz: 166.95,
      fusionZone: 169.07,
    },
    visualInspection: "Uniform bead appearance reported; visual appearance is not a quality conclusion.",
    sourceWarnings: [
      "One coupon only; no dispersion or inferential statistics are available.",
    ],
  },
  {
    id: "smaw-170",
    specimen: "SMAW 170 A",
    process: "SMAW",
    current: 170,
    travelSpeed: 7.35,
    initialMass: 4.082,
    finalMass: 3.384,
    massLossPercent: 17.1,
    corrosionRate: 25.27,
    finalMeasurementDay: 28,
    ocpMonitoredToDay: 28,
    microstructureStatus: "complete",
    microstructureScore: 75,
    microstructureNote:
      "EDS (Phenom 15kV): 72.81 wt% Fe, 18.81 wt% Cr, 6.23 wt% Ni. Evidence of localized degradation with 0.56 wt% Cl, 0.37 wt% Na, and 0.31 wt% S detected. XRD: 51(4) wt% Fe, 31(4) wt% Cr, 17.9(16) wt% Ni, crystallite size 147 Å.",
    hardness: {
      baseMetal: 180,
      haz: 171.25,
      fusionZone: 170.93,
    },
    visualInspection: "Uniform bead appearance reported; visual appearance is not a quality conclusion.",
    sourceWarnings: [
      "One coupon only; no dispersion or inferential statistics are available.",
    ],
  },
  {
    id: "smaw-180",
    specimen: "SMAW 180 A",
    process: "SMAW",
    current: 180,
    travelSpeed: 7.71,
    initialMass: 5.776,
    finalMass: 5.065,
    massLossPercent: 12.31,
    corrosionRate: 25.75,
    finalMeasurementDay: 28,
    ocpMonitoredToDay: 28,
    microstructureStatus: "missing",
    microstructureScore: 70,
    microstructureNote: "SEM, EDS, and XRD characterization were not completed for this condition.",
    hardness: {
      baseMetal: 180,
      haz: 168.16,
      fusionZone: 172.47,
    },
    visualInspection: "Uniform bead appearance reported; visual appearance is not a quality conclusion.",
    sourceWarnings: [
      "Microstructural evidence is unavailable for this condition.",
      "One coupon only; no dispersion or inferential statistics are available.",
    ],
  },
  {
    id: "gmaw-160",
    specimen: "GMAW 160 A",
    process: "GMAW",
    current: 160,
    travelSpeed: 6.1,
    initialMass: 4.416,
    finalMass: 3.454,
    massLossPercent: 21.78,
    corrosionRate: 34.83,
    finalMeasurementDay: 28,
    ocpMonitoredToDay: 28,
    microstructureStatus: "complete",
    microstructureScore: 65,
    microstructureNote:
      "EDS (Phenom 15kV): 72.38 wt% Fe, 17.09 wt% Cr, 7.64 wt% Ni, 0.95 wt% Ca, 0.76 wt% Cu, 0.63 wt% Mn; 0.00% Cl and 0.00% Na. XRD: 2θ = 43.99°, d = 2.057 Å, crystallite size 175 Å with Fe, Cr, Ni phases.",
    hardness: {
      baseMetal: 180,
      haz: 168.08,
      fusionZone: 168.52,
    },
    visualInspection: "Weld visually inspected in the reported study.",
    sourceWarnings: [
      "One coupon only; no dispersion or inferential statistics are available.",
    ],
  },
  {
    id: "gmaw-170",
    specimen: "GMAW 170 A",
    process: "GMAW",
    current: 170,
    travelSpeed: 4.66,
    initialMass: 5.533,
    finalMass: 4.63,
    massLossPercent: 16.32,
    corrosionRate: 32.7,
    finalMeasurementDay: 28,
    ocpMonitoredToDay: 28,
    microstructureStatus: "missing",
    microstructureScore: 60,
    microstructureNote: "SEM, EDS, and XRD characterization were not completed for this condition.",
    hardness: {
      baseMetal: 180,
      haz: 171.72,
      fusionZone: 169.72,
    },
    visualInspection: "Weld visually inspected in the reported study.",
    sourceWarnings: [
      "Microstructural evidence is unavailable for this condition.",
      "One coupon only; no dispersion or inferential statistics are available.",
    ],
  },
  {
    id: "gmaw-180",
    specimen: "GMAW 180 A",
    process: "GMAW",
    current: 180,
    travelSpeed: 6.39,
    initialMass: 5.918,
    finalMass: 5.012,
    massLossPercent: 15.31,
    corrosionRate: 32.81,
    finalMeasurementDay: 28,
    ocpMonitoredToDay: 28,
    microstructureStatus: "complete",
    microstructureScore: 55,
    microstructureNote:
      "EDS (Phenom 15kV): 82.66 wt% Fe, 6.21 wt% Cr (severe chromium depletion), 3.31 wt% Ni, 2.45 wt% Zn, 1.91 wt% Cu, 1.06 wt% Mg, 0.97 wt% Si. Depletion explains high corrosion rate. XRD: 2θ = 44.16°, crystallite size 188 Å.",
    hardness: {
      baseMetal: 180,
      haz: 173.6,
      fusionZone: 171.83,
    },
    visualInspection: "Weld visually inspected in the reported study.",
    sourceWarnings: [
      "One coupon only; no dispersion or inferential statistics are available.",
    ],
  },
  {
    id: "control",
    specimen: "Unwelded control",
    process: "Control",
    current: null,
    travelSpeed: null,
    initialMass: 3.998,
    finalMass: 3.324,
    massLossPercent: 16.86,
    corrosionRate: 24.41,
    finalMeasurementDay: 28,
    ocpMonitoredToDay: 28,
    microstructureStatus: "complete",
    microstructureScore: 90,
    microstructureNote:
      "EDS (Phenom 15kV): 73.91 wt% Fe, 17.27 wt% Cr, 7.46 wt% Ni, 0.71 wt% Ti, 0.33 wt% C; 0.00% Cl/Na/S (nominal AISI 304 baseline). XRD: 47(9) wt% Fe, 26(6) wt% Cr, 27(12) wt% Ni; 2θ = 44.10°, crystallite size 180 Å.",
    hardness: {
      baseMetal: 180,
      haz: 180,
      fusionZone: 180,
    },
    visualInspection: "Unwelded comparative control.",
    sourceWarnings: [
      "Control is for comparison only and is excluded from weld-process ranking.",
      "One coupon only; no dispersion or inferential statistics are available.",
    ],
  },
];
